# Syntax 
# <Teilstring des resourcennamens>:<segment/db name>:<Primary Key Field>
#
park + ride anlagen in koeln:parkandride:FID
parkscheinautomaten koeln 2016:psa:PSA-Nr
tankstellen:tankstellen:OBJECTID
wohnungsverteilung stadtbezirke koeln 2014:wohnverteilung:Stadtbezirke
spiel- und sportplaetze in koeln:spielsport:OBJECTID
wohnen in koeln:wohnen:feeds_flatstore_entry_id
wochenmaerkte:wochenmaerkte:objectId
Verwaltungsgebaeude Alter Gebaeudewirtschaft Koeln:gebaeudealtersstruktur:WE
Schulen Alter Gebaeudewirtschaft Koeln:gebaeudealtersstruktur:WE
Kindertagesstaetten Alter Gebaeudewirtschaft Koeln:gebaeudealtersstruktur:WE
Bauprojekte staedtische Gebaeude:staedtischebauprojekte:OBJECTID
Bauprojekte in Köln:bauprojekte:OBJECTID
baufertigstellungen koeln stadtbezirk:baufertigstellungen:feeds_flatstore_entry_id
Krankenhäuser in Köln:krankenhaeuser:OBJECTID
summe erzeugter und entsorgter abfaelle koeln 2013:abfallbilanz:feeds_flatstore_entry_id
Abfallarten entsorgte Abfallmenge Koeln 2013:entsorgterabfall:feeds_flatstore_entry_id
abfallarten erzeugte abfallmenge koeln 2013:erzeugterabfall:feeds_flatstore_entry_id
parkhausbelegung:parkhausbelegung:IDENTIFIER
fahrradstraßen koeln:fahrradstrassen:lfd Nummer
strassenbeschränkung:strassenbeschraenkungen:Laufende_Nummer
haltestellen stadtbahn u-bahn koeln:haltestellenbahn:KNOTENNUMMER
zaehldaten 2010 - 2016 knoten:kfzwerte:NO
umweltzone:umweltzone:OBJECTID
lkw verbotszone köln:lkwverbot:OBJECTID
strecke stadtbahn u-bahn koeln:streckebahn:STRECKENNUMMER
lkw verbindungen koeln:lkwverbindung:OBJECTID
postleitzahlgebiete:postleitzahlgebiete:OBJECTID
#
# Flächennutzungsplan
#
fnp tunnellage:fnptunnel:OBJECTID
fnp sanierungsgebiete:fnpsanierung:OBJECTID
fnp naturschutz:fnpnaturschutz:OBJECTID
fnp verkehrsstrasse:fnpverkehr:OBJECTID
fnp aktuell:fnpaktuell:OBJECTID
#
# Errors - Server error
#
#hundefreilaufflaechen-koeln:hundefreilaufflaechen:
#stadtgebiet:stadtgebiet:OBJECTID